version: "2"
services:
  web:
    build: "."
    volumes:
      - .:/home/user/code
    environment:
      - PORT=80
    ports:
      - "5000:80"
    command: "node server.js"
    entrypoint: /home/user/setup.sh
  bash:
    build: '.'
    volumes:
      - .:/home/user/code
    command: "bash"
    depends_on:
      - web
  benchmark:
    image: "hone/faban"
    volumes:
      - ./results:/home/user/results
    depends_on:
      - web
    command: "bash"
